### PR TITLE
Updated css to change the halo focus color

### PR DESCRIPTION
**Pull request by noahgelman**
## Description
Adds a new color and updates the focus color

https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/359

2nd related PR: https://github.com/department-of-veterans-affairs/component-library/pull/175

## Definition of done
- [ ] Not blue colored focused elements have an olive colored focus ring

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
From the linked issue:

> The ultimate solution would be an inverted look a la GOV.UK but this is just to mitigate the current problematic yellow-on-light situation.

Does this mean that the olive solution is only temporary? I'm asking because I'm wondering how to implement this in our web components. Right now we have a [mixin](https://github.com/department-of-veterans-affairs/component-library/blob/web-components/src/mixins/focusable.css) that we import when we're defining a component that can grab focus.

**Comment by noahgelman** [comment]
@bkjohnson Can you re-review? Would like to move to staging for additional review

**Review by bkjohnson — COMMENTED** [review]
The change seems ok, but I'd like to hold off on merging & publishing a new release until a new PR for https://github.com/department-of-veterans-affairs/component-library/pull/175 is also ready to go. Publishing `formation` and `component-library` at the same time seems like a good plan so that the outlines will be the same regardless of the kind of component being used.

**Comment by timwright12** [comment]
@bkjohnson Do you want to close this one out?

**Comment by bkjohnson** [comment]
Closing, work will continue for https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/654

**Pull request closed without merging**
