### PR TITLE
Sidebar causes page to not scroll: 18507

### PR DESCRIPTION
**Pull request by accbjt**
Sidebar causes page to not scroll when open. This only happens when going from mobile to desktop.

Steps:
1. Go to a page that has the sidebar.
2. Go to mobile.
3. Click on `more in this section`
4. Adjust to desktop browser size.
5. The page should scroll

Here's a screenshot of what it should do:

### CODE REVIEW

**Comment by jaredcunha-usds** [comment]
Is this a bug from putting the script in Formation? I didn’t think va.gov used formation.js. Should there be a similar fix on vets-website?

**Comment by accbjt** [comment]
This fix is for formation.js to work on vets-website. It uses the sidebar. Once this is merged I can integrate formation.js into vets-website.

**Comment by jaredcunha-usds** [comment]
Oh okay, cool. Just ran a test on this and it's not working locally on the design system. One other thing is that it's scrolling up to the top of the page as well. 

Screen Recording 2019-05-10 at 10 45 AM

**Comment by accbjt** [comment]
My change shouldn’t have effected this but let me take a look at it.

**Comment by jaredcunha-usds** [comment]
That was just something I extra I had noticed. This does not seem to happen on VA.gov.  

Locally, I added a `console.log()` function to `closeMenu()`. The function is running when it's supposed to, but it looks like everything else is inside a `click` event? https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/9327e681de7f176214f120231f8960c000c8b3a7/packages/formation/js/sidenav.js#L131

**Comment by jaredcunha-usds** [comment]
So here's what i was testing:

```
closeMenu() {
    const close = this.menu.querySelector('.va-sidebarnav-close');
    console.log('close function') // ADDED ONLY THIS LINE
    close.addEventListener('click', () => {
      this.menu.classList.remove('va-sidebarnav--opened');
      this.menu.setAttribute('aria-hidden', 'true');
      document.getElementsByTagName('body')[0].style.overflow = 'initial';
      document
        .getElementsByClassName('va-btn-sidebarnav-trigger')[0]
        .removeAttribute('hidden');
      this.removeListeners();
    });
  }
```

Screen Recording 2019-05-10 at 01 18 PM

**Comment by accbjt** [comment]
@jaredcunha-usds I think this is resolved so I am going to merge this.

**Pull request merged**
