### PR TITLE
Remove now-unused emergency-banner styles

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description

This PR is just removing unused styles for the `vads-c-emergency-banner` CSS class. The class was [removed in this PR](https://github.com/department-of-veterans-affairs/component-library/pull/180/files#diff-b5820984c1f147e5f2c7a35b5603aea615b52ba60a8bf90234bf60d0ef978772L140). I did a search in `vets-website`, `component-library`, and `content-build`, and this class doesn't appear to be used anywhere else.

The sass file itself also doesn't seem to be imported in `vets-website` or `formation`:

image

image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Changes have been tested in vets-website
- [ ] Changes have been tested in IE11, if applicable
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by kelsonic — APPROVED** [review]
lgtm! ✅

**Comment by timwright12** [comment]
@bkjohnson should this be closed out?

**Comment by bkjohnson** [comment]
No, I'd still like to remove these styles since they're unused. Just need a review.

**Comment by timwright12** [comment]
@k80bowman ^

**Comment by k80bowman** [comment]
Since this PR has been stale for a while, can you please check again and make sure these styles are still unused?

**Comment by bkjohnson** [comment]
It's still unused:

Ripgrep for "vads-c-emergency-banner" in vets-website showing zero results

Ripgrep for "vads-c-emergency-banner" in content-build showing zero results

But since this represents a breaking change and we're not ready to publish another breaking change due to the changes to box-shadow focus styling, I'm going to close this until we can pair it with other unused CSS removal.

**Pull request closed without merging**
