### PR TITLE
39750 Add Calc to Math Variables

### PR DESCRIPTION
**Pull request by pdavies88**
## Description
Add calc around math variables

## Closes
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39750

## Acceptance criteria
- [ ] Add in calc

## Definition of done
- [ ] Changes have been tested in vets-website
- [ ] Changes have been tested in IE11, if applicable
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by pdavies88** [comment]
@andresriveratoro @bkjohnson @k80bowman do you think we should publish a new version of Formation with this change?

**Comment by k80bowman** [comment]
We'll need to in order to use this on our documentation site, correct? We'll want to spot check uses in vets-website and content-build before upgrading the dependency there, though.

**Review by k80bowman — APPROVED** [review]

**Comment by pdavies88** [comment]
@k80bowman yes we would need to change the dependency to the new version for the documentation repo for this change to take effect. I will also test on vets-website and include a screen shot of the results

**Review by bkjohnson — COMMENTED** [review]
Yeah, a patch version would be good to fix the sass warning in the documentation site.

**Review by bkjohnson — APPROVED** [review]

**Comment by pdavies88** [comment]
@k80bowman @humancompanion-usds @bkjohnson this updates causes a failure on Vets Website as it forces the variable of $multiple to be locked and not converted to a pixel value.

Screenshot here of before the change:
Screen Shot 2022-04-14 at 9 13 17 AM

Screenshot after the change showing the failure:
Screen Shot 2022-04-14 at 9 23 15 AM

Since we use spacers for all of the `.vads-u-padding--` and `.vads-u-margin--` we probably should just leave as is and instead suppress the error message in the documentation site.

**Comment by pdavies88** [comment]
Issue solved per Katy's comment: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39750#issuecomment-1099196119

**Pull request merged**
