### PR TITLE
882 Negative Margin Spacers Fix

### PR DESCRIPTION
**Pull request by pdavies88**
## Description
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/882

## Testing done / Screenshots
Screen Shot 2022-06-17 at 1 38 34 PM
Screen Shot 2022-06-17 at 1 39 14 PM
Screen Shot 2022-06-17 at 1 39 59 PM

## Acceptance criteria
- [X] Fix Negative Margin utility class

## Definition of done
- [X] Changes have been tested in vets-website
- [ ] Changes have been tested in IE11, if applicable
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by andresriveratoro — APPROVED** [review]
LGTM - Do we know why Storybook handles this without a problem?

**Comment by pdavies88** [comment]
> LGTM - Do we know why Storybook handles this without a problem?

Not sure I am assuming we have more update scss compiler packages than vets website

**Review by k80bowman — APPROVED** [review]

**Review by bkjohnson — DISMISSED** [review]
I'm doing this to prevent a merge and publish since version 8 of formation has the focus style changes that are still up in the air.

**Comment by k80bowman** [comment]
@bkjohnson is there a way we can get this fix in without deploying the focus style changes?

**Comment by bkjohnson** [comment]
When this gets published, we need to make sure that the version of `formation` used in `vets-website` is the 7.X version

**Pull request merged**
